#pragma once

#define HOOK_TYPE int

#define HOOK_NULL 0

#define HOOK_CONTINUOUS 1
	#define HOOK_CONTINUOUS_STR "CONTINUOUS"
	#define HOOK_CONTINUOUS_ARGS 0
#define HOOK_EVENT_DISABLED 2
	#define HOOK_EVENT_DISABLED_STR "EVENT_DISABLED"
	#define HOOK_EVENT_DISABLED_ARGS 1
#define HOOK_STATE_ENTERED 3
	#define HOOK_STATE_ENTERED_STR "STATE_ENTERED"
	#define HOOK_STATE_ENTERED_ARGS 1
#define HOOK_START 4
	#define HOOK_START_STR "START"
	#define HOOK_START_ARGS 0
#define HOOK_TIMER 5
	#define HOOK_TIMER_STR "TIMER"
	#define HOOK_TIMER_ARGS 1



